### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rrybarczyk** [rrybarczyk/strs#1]
- [x] Read files from the command line
- [ ] Implement all options from strings
- [ ] Be utf-8 aware
- [ ] Support various text encodings
